In [1]:
import os.path as osp

In [2]:
osp.join('dukemtmcreid', 'bounding_box_train')

'dukemtmcreid\\bounding_box_train'

In [20]:
import cv2

In [31]:
img1 = cv2.imread("./data/Small_Scenes_1/bounding_box_test/000000020690756_c1.jpg")

In [32]:
img1.shape

(90, 33, 3)

In [ ]:
img1.shape

(43, 16, 3)

In [ ]:
img1.shape

(220, 87, 3)

In [1]:
import pickle
import numpy as np

In [2]:
with open('dist_mat.pkl', 'rb') as f:
    dist_mat = pickle.load(f)

In [7]:
dist_mat.shape

(2228, 17644)

In [8]:
indices = np.argsort(dist_mat, axis=1)

In [10]:
k = 0
indices[k][:9]

array([10322,  7836, 10416,  7161,  2997,  3006, 16819,  7162,  8209],
      dtype=int64)

In [11]:
dist_mat[k][indices[k][:19]]

array([0.9076929 , 0.99029905, 0.9931112 , 1.0152463 , 1.0378352 ,
       1.0379802 , 1.046651  , 1.0483134 , 1.0536082 , 1.0537959 ,
       1.0563135 , 1.0598186 , 1.0644292 , 1.0669377 , 1.0684431 ,
       1.0714964 , 1.0759674 , 1.0764204 , 1.0785763 ], dtype=float32)

In [192]:
a = np.array([1,2,3])

In [193]:
a > 0

array([ True,  True,  True])

In [8]:
import os
from collections import Counter

In [11]:
root = "./data/Small_Scenes/"
folder_paths = ['bounding_box_test', 'query', 'query_1', 'query_2', 'query_3', 'query_4', 'query_5', 'query_6', 'query_7', 'query_8', 'query_9', 'query_10', 'query_11']
for i, x in enumerate(folder_paths):
    folder_path = root + x
    file_list = os.listdir(folder_path)
    
    cnt = Counter()
    for file in file_list:
        f_id = int(file.split("_")[0])
        if cnt[f_id] != i:
            file_name = folder_path + '/' + file
            os.remove(file_name)
        cnt[f_id] += 1
    

In [2]:
import pickle

# 读取 pickle 文件
with open('dist_mat.pkl', 'rb') as file:
    dist_mat = pickle.load(file)

In [11]:
dist_mat.shape

(18, 23612)

In [14]:
print(list(dist_mat[0]))

[1.2078782, 1.5865172, 0.5938792, 0.6897091, 1.0614175, 0.95691574, 0.6260371, 0.76906085, 0.77209246, 0.9814245, 0.800411, 1.2115827, 1.5864038, 0.6115986, 0.76311314, 0.9966432, 0.9913363, 0.6260371, 0.75367934, 0.7821984, 0.95018744, 0.7250151, 1.2168347, 1.5792866, 0.54952806, 0.71967775, 0.9939152, 1.0938773, 0.6325771, 0.7712773, 0.7823037, 0.9530715, 0.7031569, 1.2172439, 1.5832938, 0.5915645, 0.63740325, 1.0482224, 0.9918655, 0.6837679, 0.7562828, 0.7861607, 0.961637, 0.725932, 1.2101479, 1.5795517, 0.61246663, 0.7883788, 1.0216148, 1.0011358, 0.63636786, 0.7575444, 0.7861607, 0.9626341, 0.8913737, 1.2252465, 1.5736692, 0.5544242, 0.8839174, 1.0216148, 1.0957518, 0.65264297, 0.7454386, 0.7477588, 0.9626341, 0.8602249, 1.2040777, 1.5354042, 0.522056, 0.846093, 1.0245832, 1.0205609, 0.66659963, 0.77713084, 0.74600816, 1.013243, 0.8301984, 1.1982335, 1.5229383, 0.5844675, 0.7725398, 1.0230159, 1.1110458, 0.66659963, 0.77643704, 0.8026957, 1.0199443, 0.89599776, 1.1953228, 1.524905

In [10]:
dist_mat[:][0]

array([1.2078782, 1.5865172, 0.5938792, ..., 0.7353674, 1.169938 ,
       0.8720801], dtype=float32)

In [18]:
with open('dist_mat.pkl', 'rb') as file:
    dist_mat1 = pickle.load(file)

In [19]:
dist_mat.shape, dist_mat1.shape

((18, 23612), (12, 28501))